require:
  - rubocop
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/LineLength:
  Max: 120

Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: []
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'

RSpec/InstanceVariable:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/FormatString:
  Enabled: false
